### ISSUE TITLE
Detailed Rule Description Not Displaying

### ISSUE THREAD

**Issue by ebromberg** [litesolutions/objectscriptquality-vscode#1]
I just installed this plugin and when I click on the context menu to get detailed description of the rule, nothing happens. 
Using VSCode 1.43,plugin version 2.0.1

**Comment by dtamajon** [comment]
Where do you open the context menu? On the output window or on code?

What do you expect to happen?

**Comment by ebromberg** [comment]
I click the light bulb in the code window and that shows the menu "Open description of rule..." When I click that nothing happens. Reading the docs seems like a new tab in VS Code would open giving more detail.

**Comment by dtamajon** [comment]
Yes, when you click on the bulb and click on a rule it should show more detail in a new tab.

Please, let us know whate VSCode you are using and any other environment variable so we can try to reproduce your situation.

**Comment by ebromberg** [comment]
Here is the output from VSCode help->About menu:
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

My java version is 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode)

Windows 10 OS Version	10.0.18363 Build 18363
Brave is my default web browser
Not sure what else you might want to know.

**Comment by ebromberg** [comment]
Was just wondering if you were able to recreate this or need anything else from me?

**Comment by dtamajon** [comment]
We are trying to reproducte the problem, for now with no success. We think there is something missing on your environment or some missconfiguration.

At the point we find what it is, we will post it.

**Comment by pmsosbeck** [comment]
I am also experiencing this exact same issue.  Eager to here the answer as the rule description seems really useful

If it helps, I downloaded the extension within VSCode and it says that the version is 2.0.1.

**Comment by dtamajon** [comment]
Hi! We have finally detected the problem. We have solved it and published a new version. Please, update your plugin and let me know if it works properly now.

**Comment by ebromberg** [comment]
Thank you. I just installed the new plugin and it is working for me.

**Comment by pmsosbeck** [comment]
It is working for me as well.  Thank you! Very helpful.
