### ISSUE TITLE
No related file in current project message

### ISSUE THREAD

**Issue by ebromberg** [litesolutions/objectscriptquality-vscode#2]
I created a new class file with just a property of type String. When I saved, it didn't appear any of the checking kicked off. However, I looked in the output for solarlint and saw this:
Start analysis
Declared extensions of language ObjectScript were converted to objectscript: **/*.cls,**/*.mac,**/*.int,**/*.inc,**/*.ro
Declared extensions of language JavaScript were converted to js: **/*.js,**/*.jsx,**/*.vue
[Info  - 10:12:19 AM] Index files
Language of file 'file:///c:/Projects/LicensingUpdate/src/User/EricTest.cls' is set to 'objectscript'
Setting filesystem encoding: UTF-8
[Info  - 10:12:19 AM] 1 files indexed
'ObjectScript Squid Sensor' skipped because there is no related file in current project
'SonarJS' skipped because there is no related file in current project

Why does it think there is no related file?

**Comment by dtamajon** [comment]
Problem in your case is that the file name has the word "Test" which are intented for testing. You can analyze it by adding the following in settings (File > Preferences > Settings > settings.json):

 "sonarlint.testFilePattern": "{}"

Default value is:
 "sonarlint.testFilePattern": "{\*\*/test/\*\*,\*\*/\*test\*,\*\*/\*Test\*}"
