### ISSUE TITLE
Add opportunity deactivate cachequality rule vscode

### ISSUE THREAD

**Issue by xoxloviwan** [litesolutions/objectscriptquality-vscode#3]
I want deactivate some cachequality rules in vscode. As it works in sonarlint rules. Is it possible?

**Comment by dtamajon** [comment]
Hi! we are working in a new update which should allow this feature (probably during September). For now, it is only possible to enable or disable rules on connected mode, ruled by server.

**Comment by dtamajon** [comment]
Please, update to latest plugin version and you will be able to disable the rules you don't need.
