### ISSUE TITLE
How to use when working server-side

### ISSUE THREAD

**Issue by gbertolottiKS** [litesolutions/objectscriptquality-vscode#5]
Hi.
I'm using this extension from a while, and it's pretty good, kudos!
But I don't find a way to make it work while working server-side, connected to some IRIS server.
I'm able to use it only when I work with a file which is saved locally: is there a way to use also server-side?
Thanks

**Comment by dtamajon** [comment]
Hi Giacomo,

There is not currently support for IRIS server-side analysis. It requires some integration with main InterSystems extension.

It is not currently in our scope as it is an old-fashion way of working with Object Script and there is no requirements from any of our customers for such support.

If you require such feature, let's meet to talk about.

**Comment by gbertolottiKS** [comment]
Hi.
I'm coming back just to see if there are some changes on this topic, since now it looks more and more common to work server-side.

Thanks in advance,
Giacomo
