### ISSUE TITLE
Parsing error detected on class prototype

### ISSUE THREAD

**Issue by jpa95** [litesolutions/objectscriptquality-vscode#7]
Hi, I am getting a weird behavior, sometimes a parsing error is reported on the following line

`Class chs.MyClass Extends (%Library.Persistent) [ Owner = {someid}, Not ProcedureBlock, SqlRowIdPrivate, SqlTableName = MyClass, StorageStrategy = GSQLStorage ]`

The weird behavior is that if I remove some of the commands like Owner , No ProcedureBlock, etc, eventually the error goes away. And i can revert the file to initial state and from then on no error is reported.

Is this and objectscriptquality question or maybe this is one the side of the InterSystems team?

Best Regards,
Joel

**Comment by dtamajon** [comment]
Hi! Some of the class modifiers are not currently supported by the parser. We are working to include them all to avoid those errors. We hope to have them included in the following weeks.

Best Regards,
Daniel

**Comment by jpa95** [comment]
Ok, thanks Daniel!
